version: 0.2
run-as: root
 
phases:
  install:
    runtime-versions:
      nodejs: 18  
    commands:
      - echo "Installing app dependencies..."
      - npm -v
      - node -v
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 611466466027.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=611466466027.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Repository URI - $REPOSITORY_URI"
      - echo "Getting Docker Env variables from parameter Store..."
      - echo "Logging into Docker Hub..."
      - docker login -u uzairmansoor -p Uzair@123
  build:
    commands:
      - ls -la
      - cd fastapi-ecs
      - docker build -t ecs-fastapi:latest -f Dockerfile .
      - docker tag ecs-fastapi:latest 611466466027.dkr.ecr.us-east-1.amazonaws.com/serverless-fastapi-ecs-service-dev:latest
  post_build:
    commands:
      - echo "Build completed on `date`"
      - IMAGE_URI="611466466027.dkr.ecr.us-east-1.amazonaws.com/serverless-fastapi-ecs-service-dev:latest"
      - docker push 611466466027.dkr.ecr.us-east-1.amazonaws.com/serverless-fastapi-ecs-service-dev:latest